### ISSUE TITLE
Identify Base LC Call Numbers

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_traject#316]
Part of #285 

# To-Do
- [x] Lop LC call numbers to identify the base
- [x] Map the base call number to `call_number_lc_ssm` field

# Questions
 - Will the un-lopped call number displayed as well? See https://github.com/psu-libraries/psulib_traject/issues/316#issuecomment-885715444

**Comment by ruthtillman** [comment]
No, we won't want to display unlopped. Those only matter in the actual record which we get from WebServices availability. We'll just want to display the bases in a sorted order.

**Comment by awead** [comment]
Original comments by @ruthtillman 

In general: This is looking really good and very exciting to see! 

Regex issues and new Regex to add:
- [x]  We need to add support for `k.1`, `k.2` and `h.1, h.2` etc to regex for vol_parts (so basically standalone "k" and "h"). Example records: 3752257, 3752276. These are part-types I hadn't encountered before! Testing sample ++
- [x]  Catkey 1443986: Really weird call number formatting with stuff like `50th YYYY`.  _Expected:_ `TK7872.O7S901`
  - [x]  Related: 79172. Need to add support for these `\d{1,3}th` (22nd, 33rd) cases. _Expected_: `HV1796.P3`
- [x]  Catkey 1793712: mostly good except `HQ1101.M72 Index Spr.1972-Feb.1974` shows up alongside correct base call numbers. Unsure what's causing that, but it's a really weird call no. _Expected_: `HQ1101.M7214 | HQ1101.M72`  (there are 2 base call nos expected)
- [x]  Catkey 175885: it's not stripping the year for some reason. _Expected_: `HD1761.F37`
- [x]  Catkey 12133277: can't figure out what's causing third base call no: `PN1997.A1M216 2014 D`. (Conversely, 22083281 and 22083276 are working fine! what's the difference?) _Expected_: ` PN1997.A1M216 2014 DVD | PN1997.A1M216 2014 Blu-ray`
  - [x] Related: 21588551. _Expected_: `PN1997.2.L66255 2017 DVD | PN1997.2.L66255 2017 Blu-ray/DVD | PN1997.2.L66255 2017 Blu-ray`
  - [ ] Related: 2208330. _Expected_: `PN1997.2.V5454 2017 Blu-ray/DVD`
- [x]  Catkey 12133574:  lots of discs showing up. Maybe in how we strip info around Blu-ray and discs? This is probably also a data consistency issue but doing remediation at scale is not terribly feasible. _Expected_: `N1995.9.J34Z38 2014 Blu-ray | N1995.9.J34Z38 2014 DVD`
- [ ]  Catkey 470399: this is a really interesting one... I think we need to strip "Microfiche" "Microfilm" IFF the call number type is LC/LCPER/DEWEY/SUDOC/NLM AND there's something preceding it. I don't know how complex this would be to implement and we can talk through it. _Expected_: `AP2.A8`
- [ ]  While this pertains to ASIS, worth revisiting when we do ASIS and checking Regex to be sure it's supported -- on catkey: 55858 we have weird dates like `Jan.1-15 1973`. There's no space between the month abbreviation, the period, and the date range. Also the dates are a range. CAT handles this by breaking it down item-by-item  which isn't really helpful. _Expected_: `Microfilm E164`

Updating logic: 

- [ ]  Catkey 71529: I noticed some odd call numbers ` NK-4600 | HA-25411` showing up coded as LC. It turns out that these are standing order records (vs. temporary order records). They read as standing order for campus (NK = New Kensington, HA = Harrisburg). A couple similar ones are under ASIS. They can be identified at the item level by `949l == ON-ORDER`. So it seems like we need logic to not index those. It would be worth checking other ON-ORDER records with the `xx(` prefix to see if we can just filter them this way too. That would make sense. _Expected_: `AP2.N6763`

Things I didn't expect to see but I think I understand, just confirming:
- [ ]  The following aren't showing a `call_number_base`, despite containing LC/LCPER/Dewey: 105498, 122553, 173833, 2183066, 3752213. These include one ASIS and one LC/Dewey type: 123730 & 213578 & 344826 & 2251805 & 2624797 & 3559984 & 10016724 - maybe will be resolved by adding ASIS so the LC/Dewey type has a thing to compare against?

**Comment by awead** [comment]
Original comments by @ruthtillman 
n general: This is looking really good and very exciting to see! 

Regex issues and new Regex to add:
- [x]  We need to add support for `k.1`, `k.2` and `h.1, h.2` etc to regex for vol_parts (so basically standalone "k" and "h"). Example records: 3752257, 3752276. These are part-types I hadn't encountered before! Testing sample ++
- [x]  Catkey 1443986: Really weird call number formatting with stuff like `50th YYYY`.  _Expected:_ `TK7872.O7S901`
  - [x]  Related: 79172. Need to add support for these `\d{1,3}th` (22nd, 33rd) cases. _Expected_: `HV1796.P3`
- [x]  Catkey 1793712: mostly good except `HQ1101.M72 Index Spr.1972-Feb.1974` shows up alongside correct base call numbers. Unsure what's causing that, but it's a really weird call no. _Expected_: `HQ1101.M7214 | HQ1101.M72`  (there are 2 base call nos expected)
- [x]  Catkey 175885: it's not stripping the year for some reason. _Expected_: `HD1761.F37`
- [x]  Catkey 12133277: can't figure out what's causing third base call no: `PN1997.A1M216 2014 D`. (Conversely, 22083281 and 22083276 are working fine! what's the difference?) _Expected_: ` PN1997.A1M216 2014 DVD | PN1997.A1M216 2014 Blu-ray`
  - [x] Related: 21588551. _Expected_: `PN1997.2.L66255 2017 DVD | PN1997.2.L66255 2017 Blu-ray/DVD | PN1997.2.L66255 2017 Blu-ray`
  - [ ] Related: 2208330. _Expected_: `PN1997.2.V5454 2017 Blu-ray/DVD`
- [x]  Catkey 12133574:  lots of discs showing up. Maybe in how we strip info around Blu-ray and discs? This is probably also a data consistency issue but doing remediation at scale is not terribly feasible. _Expected_: `N1995.9.J34Z38 2014 Blu-ray | N1995.9.J34Z38 2014 DVD`
- [ ]  Catkey 470399: this is a really interesting one... I think we need to strip "Microfiche" "Microfilm" IFF the call number type is LC/LCPER/DEWEY/SUDOC/NLM AND there's something preceding it. I don't know how complex this would be to implement and we can talk through it. _Expected_: `AP2.A8`
- [ ]  While this pertains to ASIS, worth revisiting when we do ASIS and checking Regex to be sure it's supported -- on catkey: 55858 we have weird dates like `Jan.1-15 1973`. There's no space between the month abbreviation, the period, and the date range. Also the dates are a range. CAT handles this by breaking it down item-by-item  which isn't really helpful. _Expected_: `Microfilm E164`

Updating logic: 

- [ ]  Catkey 71529: I noticed some odd call numbers ` NK-4600 | HA-25411` showing up coded as LC. It turns out that these are standing order records (vs. temporary order records). They read as standing order for campus (NK = New Kensington, HA = Harrisburg). A couple similar ones are under ASIS. They can be identified at the item level by `949l == ON-ORDER`. So it seems like we need logic to not index those. It would be worth checking other ON-ORDER records with the `xx(` prefix to see if we can just filter them this way too. That would make sense. _Expected_: `AP2.N6763`

Things I didn't expect to see but I think I understand, just confirming:
- [ ]  The following aren't showing a `call_number_base`, despite containing LC/LCPER/Dewey: 105498, 122553, 173833, 2183066, 3752213. These include one ASIS and one LC/Dewey type: 123730 & 213578 & 344826 & 2251805 & 2624797 & 3559984 & 10016724 - maybe will be resolved by adding ASIS so the LC/Dewey type has a thing to compare against?

**Comment by ruthtillman** [comment]
Review of 2021-07-29 call number base file from @awead, only 2 issues, 2 additions:

## Additions

* [ ] add "Newspaper" to "Periodical" for ignoring. This is another one we can't order in any meaningful way.

* [ ] `3749921      call_number_lc_ssm        DS118.R587 1927 Tl.1 | DS118.R587 1927 Tl.2` - add test for "Tl" (teil, or "part" in German)

## Issues

* [ ] When H or K are _inside_ the cutter sections of the call number, they're getting cut off, kind of like the "V" in "DVD" issue.
 
```
2101414      call_number_lc_ssm        QA76.9.D3
      should be QA76.9.D3H365153 2000 - all 3 call nos. are identical. - expect to behave like https://catalog.libraries.psu.edu/catalog/2146375
3751038      call_number_lc_ssm        PJ5129.A8
      should be PJ5129.A8K65
```

* [ ] There was one instance where it didn't catch "h" parts for some reason.

```
3752276      call_number_lc_ssm        BM520.88.A52I87 1952 ḥ.1 | BM520.88.A52I87 1952 ḥ.6 | BM520.88.A52I87 1952 ḥ.3 | BM520.88.A52I87 1952 ḥ.4 | BM520.88.A52I87 1952 ḥ.2 | BM520.88.A52I87 1952 ḥ.5
```

## Additional Notes

The bound-with stuff seems on track. They're all "on shelf" together, but they're separate works, just in the same book vs. beside each other with covers separating them. We'll have to keep in mind the several ways we can get repeated call numbers when sorting/displaying. Might make the most sense just to order secondarily by title or something when they occur.

**Comment by awead** [comment]
@ruthtillman Here's the issue with H and K in cutters. When H or K occurs as the second letter, it's matching the regex for "k" and "h" as volume designations.

    QA76.9.D3H365153 2000

Evaluates the same as:

    QA76.9.D3 h.3

I tried doing case-sensitive matching, but that makes the problem worse. What seems to work is to be more specific about the volume designation, the "h.3" part. Can you tell me more about what we should expect for these:

1. Is the period always there?
2. Are they longer than 2 digits?
3. Are they always at the very end of the call number?

If the period is _always_ there, then as long as there aren't any cutters like QA76.9.D3.H3 then we should be good.

**Comment by ruthtillman** [comment]
@awead is there any way to test if there's a space before the h or the k? Like using an actual \s? I know spaces are the messiest part of this, but I can say with 100% certainty that there would be a space before the h.3*

1. The period should also always be there.*
2. I can't say whether we'll ever have more than 2 digits... seems unlikely but some things do get broken up weirdly.
3. They should generally be at the end BUT I can't guarantee that there aren't maybe `QA76.9.D3.H3` somewhere :-/ 

*that or the person would've messed up on the data side and then that's an error to be fixed in Workflows, not by us
