### ISSUE TITLE
Generate and Index LC Shelf Keys

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_traject#317]
# To-Do
- [x] normalize call numbers using `lcsort` gem
- [x] use normalized call number as forward shelf key
- [x] generate reverse shelf key from forward shelf key, ex:
```return the reverse String value, mapping A --> 9, B --> 8, ... 9 --> A and also non-alphanum to sort properly (before or after alphanum)```
- [x] map the keys to `lc_forward_shelf_key` and `lc_reverse_shelf_key` fields

**Comment by awead** [comment]
## Incorrect LC Numbers

Lcsort will return `nil` if it can't determine a proper forward key. Currently, we then determine a our own which is causing browsing problems. Ex, give a call number like `EC 1.1201/1:E 97/`

```
> Lcsort.normalize('EC 1.1201/1:E 97/')
=> nil
```

So we can make our "best guess" and try to coax it into something.

## Questions

1. Should we _always_ return something even if may be wrong, or return nil if we can't correctly determine the key?

**Comment by banukutlu** [comment]
> 3. Can we use SIRSI?

If we can get promising results from #327, I would be inclined toward the this 3rd option.

**Comment by awead** [comment]
> 2. Should be make our own shelfkey generator, like Stanford?

We don't have to start from scratch. The `Lcsort` gem is getting the vast majority of them: 35K out of 2.7M. We can focus on the ones that aren't working.

**Comment by banukutlu** [comment]
Can we ignore these and log it so we can catch them periodically?

> ## Incorrect LC Numbers
> Lcsort will return `nil` if it can't determine a proper forward key. Currently, we then determine a our own which is causing browsing problems. Ex, give a call number like `EC 1.1201/1:E 97/` in https://catalog.libraries.psu.edu/catalog/1655210
> 
> ```
> > Lcsort.normalize('EC 1.1201/1:E 97/')
> => nil
> ```
> 
> So we can make our "best guess" and try to coax it into something.
> 

question from kickoff meeting: can we ignore these and log it so we can catch them periodically?

**Comment by ruthtillman** [comment]
Recording some of the patterns I've identified from the list of 35,000 call # not processing:

1. `^XX(` - while our script is catching the ones that begin with `xx(` apparently there's also some with XX(... these seem to be a bit older so maybe it's LIAS-type stuff? Anyway, solution for this would be to make it case-insensitive since we should never have a _valid_ call number beginning with `XX(` or `xx(`. (2021 items)
2. `(.+?)\.(.+?)./(.+?)\:(.+?)` - this regex pattern appears to catch all the SUDOC stuff, which I can pull out into a spreadsheet for remediation. I can discuss our options with Maryam -- one issue is that we only have catkeys vs. actual item IDs but I have some ideas about that. (3310 items)
3. Contains lowercase author name after valid LC. Examples: PZ7.L169653Cro 2015, PZ7.H56774Fou 2014, PZ7.H1996Mad 2014, PZ7.I7629Red 2015, LD4481.P8kG45 2008, PZ7.7.F39Gai 2014, PZ8.3.Y26Iak 2014, PZ7.B7633Cjip 2014, PZ8.3.L97128Ang 2013 - these are how a lot of children's books are done and they're mostly-valid LC with a weird author 3-letter name part stuck on. Ideally we could figure out how to handle these :-/ (11,930 items)
4. K.Eu74pS888 - etc. ... I think these are European gov docs and should be treated as ASIS. I think I can get a regex for them. (only 138)
5. Related to no. 3, there's a number which are showing up because they have a random lower-case number somewhere in them, from `KKP.B634b` to `KJD.In8i` - is this something we could solve together with 3? (no easy way to count these)
6. Call no. starts with Micro - these should be moved to ASIS. (110 items.)
7. Call number is only "Periodical" - I think there's a note somewhere to exclude that. (847 items)

I also found a few more "volume/part" type things from other languages that I'll work on pulling together. - Polish, Czech, that kind of thing.

This isn't 100% but it covers a lot of the things I've run into.

**Comment by awead** [comment]
Given the feedback above, I'm proposing the following:
> Update traject:

* update `CallNumber` to ignore records with `XX(` call numbers
* find out why "Periodical" isn't being excluded -- this is supposed to happen in `CallNumber` also

> Update sort:

* create an additional normalization function in `ShelfKey` to correctly process those three cases into a valid forward key, ex: `Lcsort.normalize(call_number) || extended_normalize(call_number) || NullKey.new`
* verify that `CallNumber::LC` is correctly identifying and reducing these to their correct base

> Update records

* nothing for us to do here, but one question for later discussion is how should we handle these moving forward?
