### ISSUE TITLE
Generate and index shelf keys for browsing authors

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_traject#330]
# To-Do
- [ ] use `all_authors_facet` for author browse
- [ ] normalize authors and generate forward shelf keys
- [ ] generate reverse shelf keys from forward shelf keys
- [ ] map the keys to `author_forward_shelf_key` and `author_forward_shelf_key` fields

**Comment by banukutlu** [comment]
not relevant
